lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.17.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "https://dsc.gg/ajidevserver"
    sources:
      youtube: false # ปิดอันเก่า
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true

plugins:
  youtube:
    enabled: true
    clients:
      - "MUSIC"
      - "ANDROID_TESTSUITE"
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\"" # ให้มันแอบไปหาเสียงจาก YouTube Music โดยอิงจากรหัสเพลง Spotify
      - "ytsearch:%QUERY%" 
    sources:
      spotify: false  
      applemusic: false
      deezer: false
      yandexmusic: false
